[[redirects]]
  from = "https://devgru.la/*"
  to = "https://d-e-v.group/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.devgru.la/*"
  to = "https://d-e-v.group/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://devgru.netlify.app/*"
  to = "https://d-e-v.group/:splat"
  status = 301
  force = true